// <auto-generated />
namespace Shoop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewAttempttoAddState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewAttempttoAddState));
        
        string IMigrationMetadata.Id
        {
            get { return "202008051752462_New Attempt to Add State"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
